-- Rebuild script for PostgreSQL schema.
-- Includes classification table definition from Activity W04.

CREATE TABLE IF NOT EXISTS public.classification (
  classification_id INT GENERATED BY DEFAULT AS IDENTITY,
  classification_name VARCHAR NOT NULL,
  CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

CREATE TABLE IF NOT EXISTS public.inventory (
  inv_id INT GENERATED BY DEFAULT AS IDENTITY,
  inv_make VARCHAR NOT NULL,
  inv_model VARCHAR NOT NULL,
  inv_year CHAR(4) NOT NULL,
  inv_description TEXT NOT NULL,
  inv_image VARCHAR NOT NULL,
  inv_thumbnail VARCHAR NOT NULL,
  inv_price NUMERIC(9, 0) NOT NULL,
  inv_miles INT NOT NULL,
  inv_color VARCHAR NOT NULL,
  inv_quantity INT NOT NULL DEFAULT 1 CHECK (inv_quantity >= 0),
  classification_id INT NOT NULL REFERENCES public.classification(classification_id),
  CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

CREATE TABLE IF NOT EXISTS public.account (
  account_id INT GENERATED BY DEFAULT AS IDENTITY,
  account_firstname VARCHAR NOT NULL,
  account_lastname VARCHAR NOT NULL,
  account_email VARCHAR NOT NULL,
  account_password VARCHAR NOT NULL,
  account_type account_type NOT NULL DEFAULT 'Client'::account_type,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT account_pkey PRIMARY KEY (account_id),
  CONSTRAINT account_email_unique UNIQUE (account_email)
);

CREATE TABLE IF NOT EXISTS public.user_profile (
  profile_id INT GENERATED BY DEFAULT AS IDENTITY,
  account_id INT NOT NULL UNIQUE REFERENCES public.account(account_id) ON DELETE CASCADE,
  bio TEXT,
  phone_number VARCHAR(20),
  address VARCHAR(255),
  profile_picture VARCHAR(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_profile_pkey PRIMARY KEY (profile_id)
);

CREATE TABLE IF NOT EXISTS public.admin_activity (
  activity_id INT GENERATED BY DEFAULT AS IDENTITY,
  admin_id INT NOT NULL REFERENCES public.account(account_id) ON DELETE CASCADE,
  action_type VARCHAR(100) NOT NULL,
  target_type VARCHAR(100),
  target_id INT,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT admin_activity_pkey PRIMARY KEY (activity_id)
);

CREATE TABLE IF NOT EXISTS public.shopping_cart (
  cart_id INT GENERATED BY DEFAULT AS IDENTITY,
  account_id INT NOT NULL REFERENCES public.account(account_id) ON DELETE CASCADE,
  inv_id INT NOT NULL REFERENCES public.inventory(inv_id) ON DELETE CASCADE,
  quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
  added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT shopping_cart_pkey PRIMARY KEY (cart_id),
  CONSTRAINT shopping_cart_unique UNIQUE (account_id, inv_id)
);

CREATE TABLE IF NOT EXISTS public.wishlist (
  wishlist_id INT GENERATED BY DEFAULT AS IDENTITY,
  account_id INT NOT NULL REFERENCES public.account(account_id) ON DELETE CASCADE,
  inv_id INT NOT NULL REFERENCES public.inventory(inv_id) ON DELETE CASCADE,
  added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT wishlist_pkey PRIMARY KEY (wishlist_id),
  CONSTRAINT wishlist_unique UNIQUE (account_id, inv_id)
);

CREATE TABLE IF NOT EXISTS public.orders (
  order_id INT GENERATED BY DEFAULT AS IDENTITY,
  account_id INT NOT NULL REFERENCES public.account(account_id) ON DELETE CASCADE,
  order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  total_amount NUMERIC(10, 2) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'shipped', 'delivered', 'cancelled')),
  CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.order_items (
  order_item_id INT GENERATED BY DEFAULT AS IDENTITY,
  order_id INT NOT NULL REFERENCES public.orders(order_id) ON DELETE CASCADE,
  inv_id INT NOT NULL REFERENCES public.inventory(inv_id) ON DELETE RESTRICT,
  quantity INT NOT NULL CHECK (quantity > 0),
  price_at_purchase NUMERIC(9, 0) NOT NULL,
  CONSTRAINT order_items_pkey PRIMARY KEY (order_item_id)
);

INSERT INTO public.classification (classification_name)
VALUES
  ('Custom'),
  ('Sport'),
  ('SUV'),
  ('Truck'),
  ('Sedun');

INSERT INTO public.inventory (
  inv_make,
  inv_model,
  inv_year,
  inv_description,
  inv_image,
  inv_thumbnail,
  inv_price,
  inv_miles,
  inv_color,
  classification_id
)
VALUES
  (
    'Chevy',
    'Camaro',
    '2018',
    'If you want to look cool this is the ar you need! This car has great performance at an affordable price. Own it today!',
    '/images/vehicles/camaro.jpg',
    '/images/vehicles/camaro-tn.jpg',
    25000,
    101222,
    'Silver',
    2
  ),
  (
    'Batmobile',
    'Custom',
    '2007',
    'Ever want to be a super hero? now you can with the batmobile. This car allows you to switch to bike mode allowing you to easily maneuver through traffic during rush hour.',
    '/images/vehicles/batmobile.jpg',
    '/images/vehicles/batmobile-tn.jpg',
    65000,
    29887,
    'Black',
    1
  ),
  (
    'FBI',
    'Surveillance Van',
    '2016',
    'Do you like police shows? You will feel right at home driving this van, comes complete with survalence equipments for and extra fee of $2,000 a month.',
    '/images/vehicles/survan.jpg',
    '/images/vehicles/survan-tn.jpg',
    20000,
    19851,
    'Brown',
    1
  ),
  (
    'Dog ',
    'Car',
    '1997',
    'Do you like dogs? Well this car is for you straight from the 90s from Aspen, Colorado we have the orginal Dog Car complete with fluffy ears.',
    '/images/vehicles/dog-car.jpg',
    '/images/vehicles/dog-car-tn.jpg',
    35000,
    71632,
    'White',
    1
  ),
  (
    'Jeep',
    'Wrangler',
    '2019',
    'The Jeep Wrangler is small and compact with enough power to get you where you want to go. Its great for everyday driving as well as offroading weather that be on the the rocks or in the mud!',
    '/images/vehicles/wrangler.jpg',
    '/images/vehicles/wrangler-tn.jpg',
    28045,
    41205,
    'Yellow',
    3
  ),
  (
    'Lamborghini',
    'Adventador',
    '2016',
    'This V-12 engine packs a punch in this sporty car. Make sure you wear your seatbelt and obey all traffic laws. ',
    '/images/vehicles/adventador.jpg',
    '/images/vehicles/adventador-tn.jpg',
    417650,
    71003,
    'Blue',
    2
  ),
  (
    'Aerocar International',
    'Aerocar',
    '1963',
    'Are you sick of rushhour trafic? This car converts into an airplane to get you where you are going fast. Only 6 of these were made, get them while they last!',
    '/images/vehicles/aerocar.jpg',
    '/images/vehicles/aerocar-tn.jpg',
    700000,
    18956,
    'Red',
    1
  ),
  (
    'Monster',
    'Truck',
    '1995',
    'Most trucks are for working, this one is for fun. This beast comes with 60 inch tires giving you traction needed to jump and roll in the mud.',
    '/images/vehicles/monster-truck.jpg',
    '/images/vehicles/monster-truck-tn.jpg',
    150000,
    3998,
    'purple',
    1
  ),
  (
    'Cadillac',
    'Escalade',
    '2019',
    'This stylin car is great for any occasion from going to the beach to meeting the president. The luxurious inside makes this car a home away from home.',
    '/images/vehicles/escalade.jpg',
    '/images/vehicles/escalade-tn.jpg',
    75195,
    41958,
    'Black',
    4
  ),
  (
    'GM',
    'Hummer',
    '2016',
    'Do you have 6 kids and like to go offroading? The Hummer gives you the small interiors with an engine to get you out of any muddy or rocky situation.',
    '/images/vehicles/hummer.jpg',
    '/images/vehicles/hummer-tn.jpg',
    58800,
    56564,
    'Yellow',
    4
  ),
  (
    'Mechanic',
    'Special',
    '1964',
    'Not sure where this car came from. however with a little tlc it will run as good a new.',
    '/images/vehicles/mechanic.jpg',
    '/images/vehicles/mechanic-tn.jpg',
    100,
    200125,
    'Rust',
    5
  ),
  (
    'Ford',
    'Model T',
    '1921',
    'The Ford Model T can be a bit tricky to drive. It was the first car to be put into production. You can get it in any color you want as long as it is black.',
    '/images/vehicles/model-t.jpg',
    '/images/vehicles/model-t-tn.jpg',
    30000,
    26357,
    'Black',
    5
  ),
  (
    'Mystery',
    'Machine',
    '1999',
    'Scooby and the gang always found luck in solving their mysteries because of there 4 wheel drive Mystery Machine. This Van will help you do whatever job you are required to with a success rate of 100%.',
    '/images/vehicles/mystery-van.jpg',
    '/images/vehicles/mystery-van-tn.jpg',
    10000,
    128564,
    'Green',
    1
  ),
  (
    'Spartan',
    'Fire Truck',
    '2012',
    'Emergencies happen often. Be prepared with this Spartan fire truck. Comes complete with 1000 ft. of hose and a 1000 gallon tank.',
    '/images/vehicles/fire-truck.jpg',
    '/images/vehicles/fire-truck-tn.jpg',
    50000,
    38522,
    'Red',
    4
  ),
  (
    'Ford',
    'Crown Victoria',
    '2013',
    'After the police force updated their fleet these cars are now available to the public! These cars come equiped with the siren which is convenient for college students running late to class.',
    '/images/vehicles/crwn-vic.jpg',
    '/images/vehicles/crwn-vic-tn.jpg',
    10000,
    108247,
    'White',
    5
  );

-- Fix image paths if they were inserted without /vehicles/ subdirectory
UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/')
WHERE inv_image LIKE '/images/%' AND inv_image NOT LIKE '/images/vehicles/%';

-- Insert sample reviews
INSERT INTO public.reviews (inv_id, account_id, rating, review_text) VALUES
(1, 1, 5, 'Excellent vehicle! Very reliable and comfortable.'),
(1, 2, 4, 'Great car, good condition. Highly recommend.'),
(2, 1, 5, 'Amazing performance and fuel efficiency.'),
(3, 3, 3, 'Good car but needs some maintenance.');

-- Insert sample ratings
INSERT INTO public.ratings (inv_id, account_id, rating) VALUES
(1, 1, 5),
(1, 2, 4),
(2, 1, 5),
(3, 3, 3),
(4, 2, 4);

-- Insert sample favorites
INSERT INTO public.favorites (inv_id, account_id) VALUES
(1, 1),
(2, 1),
(3, 2),
(4, 3);

-- Insert sample shopping cart items
INSERT INTO public.shopping_cart (account_id, inv_id, quantity) VALUES
(1, 1, 1),    -- Account 1 has Camaro in cart
(1, 5, 2),    -- Account 1 has Wrangler in cart (quantity 2)
(2, 2, 1),    -- Account 2 has Batmobile in cart
(3, 7, 1);    -- Account 3 has Aerocar in cart

